## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(['EIN','NAME'], axis=1)

In [7]:
# Determine the number of unique values in each column.
value_counts = application_df.nunique()
print(value_counts)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [14]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_type_counts)

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [15]:
# Choose a cutoff value and create a list of application types to be replaced
cutoff_value = 500
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = application_df['APPLICATION_TYPE'].value_counts()\
[application_df['APPLICATION_TYPE'].value_counts() < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [17]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [24]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
classification_greater1 = classification_counts[classification_counts > 1]
print(classification_greater1)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [29]:
# Choose a cutoff value and create a list of classifications to be replaced
cutoff_value = 500
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [48]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
categorical_dummies = pd.get_dummies(application_df)
categorical_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [49]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
X = categorical_dummies.drop(columns=['IS_SUCCESSFUL'], axis=1)
y = categorical_dummies['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 1)

In [50]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [47]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
input_features = X_train.shape[1]


nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=80, activation='relu', input_dim=input_features))

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 80)                3520

 dense_10 (Dense)            (None, 30)                2430

 dense_11 (Dense)            (None, 1)                 31

=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

## Compile, Train and Evaluate the Model

In [51]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
input_features = X_train.shape[1]


nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=80, activation='relu', input_dim=input_features))

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 80)                3520

 dense_13 (Dense)            (None, 30)                2430

 dense_14 (Dense)            (None, 1)                 31

=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [54]:
# compile the model
#  YOUR CODE GOES HERE
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [55]:
# Train the model
#  YOUR CODE GOES HERE
train_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
751/751 [==============================] - 3s 2ms/step - loss: 0.5726 - accuracy: 0.7200 - val_loss: 0.5585 - val_accuracy: 0.7282
Epoch 2/100
751/751 [==============================] - 2s 3ms/step - loss: 0.5560 - accuracy: 0.7287 - val_loss: 0.5560 - val_accuracy: 0.7319
Epoch 3/100
751/751 [==============================] - 5s 7ms/step - loss: 0.5534 - accuracy: 0.7305 - val_loss: 0.5543 - val_accuracy: 0.7312
Epoch 4/100
751/751 [==============================] - 5s 6ms/step - loss: 0.5511 - accuracy: 0.7313 - val_loss: 0.5542 - val_accuracy: 0.7296
Epoch 5/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5503 - accuracy: 0.7316 - val_loss: 0.5541 - val_accuracy: 0.7336
Epoch 6/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5488 - accuracy: 0.7319 - val_loss: 0.5530 - val_accuracy: 0.7318
Epoch 7/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5481 - accuracy: 0.7331 - val_loss: 0.5553 - val_accuracy: 0.7304
Epoch 8/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5477 - accuracy: 0.7312 - val_loss: 0.5556 - val_accuracy: 0.7315
Epoch 9/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5467 - accuracy: 0.7335 - val_loss: 0.5557 - val_accuracy: 0.7264
Epoch 10/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5459 - accuracy: 0.7337 - val_loss: 0.5537 - val_accuracy: 0.7304
Epoch 11/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5450 - accuracy: 0.7343 - val_loss: 0.5520 - val_accuracy: 0.7313
Epoch 12/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5452 - accuracy: 0.7344 - val_loss: 0.5533 - val_accuracy: 0.7300
Epoch 13/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5443 - accuracy: 0.7341 - val_loss: 0.5523 - val_accuracy: 0.7316
Epoch 14/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5448 - accuracy: 0.7346 - val_loss: 0.5506 - val_accuracy: 0.7311
Epoch 15/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5435 - accuracy: 0.7354 - val_loss: 0.5525 - val_accuracy: 0.7302
Epoch 16/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5434 - accuracy: 0.7351 - val_loss: 0.5512 - val_accuracy: 0.7313
Epoch 17/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5435 - accuracy: 0.7361 - val_loss: 0.5510 - val_accuracy: 0.7300
Epoch 18/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5429 - accuracy: 0.7369 - val_loss: 0.5517 - val_accuracy: 0.7298
Epoch 19/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5425 - accuracy: 0.7355 - val_loss: 0.5514 - val_accuracy: 0.7289
Epoch 20/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5417 - accuracy: 0.7371 - val_loss: 0.5533 - val_accuracy: 0.7297
Epoch 21/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5423 - accuracy: 0.7365 - val_loss: 0.5503 - val_accuracy: 0.7301
Epoch 22/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5417 - accuracy: 0.7364 - val_loss: 0.5521 - val_accuracy: 0.7315
Epoch 23/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5416 - accuracy: 0.7362 - val_loss: 0.5519 - val_accuracy: 0.7279
Epoch 24/100
751/751 [==============================] - 5s 6ms/step - loss: 0.5407 - accuracy: 0.7366 - val_loss: 0.5526 - val_accuracy: 0.7317
Epoch 25/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5411 - accuracy: 0.7361 - val_loss: 0.5513 - val_accuracy: 0.7304
Epoch 26/100
751/751 [==============================] - 5s 6ms/step - loss: 0.5404 - accuracy: 0.7375 - val_loss: 0.5516 - val_accuracy: 0.7303
Epoch 27/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5405 - accuracy: 0.7379 - val_loss: 0.5521 - val_accuracy: 0.7277
Epoch 28/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5404 - accuracy: 0.7363 - val_loss: 0.5553 - val_accuracy: 0.7261
Epoch 29/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5402 - accuracy: 0.7369 - val_loss: 0.5531 - val_accuracy: 0.7315
Epoch 30/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5401 - accuracy: 0.7373 - val_loss: 0.5553 - val_accuracy: 0.7296
Epoch 31/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5396 - accuracy: 0.7371 - val_loss: 0.5522 - val_accuracy: 0.7294
Epoch 32/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5398 - accuracy: 0.7369 - val_loss: 0.5525 - val_accuracy: 0.7289
Epoch 33/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5393 - accuracy: 0.7376 - val_loss: 0.5520 - val_accuracy: 0.7302
Epoch 34/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5395 - accuracy: 0.7369 - val_loss: 0.5556 - val_accuracy: 0.7281
Epoch 35/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5393 - accuracy: 0.7373 - val_loss: 0.5520 - val_accuracy: 0.7307
Epoch 36/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5390 - accuracy: 0.7383 - val_loss: 0.5531 - val_accuracy: 0.7307
Epoch 37/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5381 - accuracy: 0.7379 - val_loss: 0.5543 - val_accuracy: 0.7301
Epoch 38/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5388 - accuracy: 0.7376 - val_loss: 0.5519 - val_accuracy: 0.7314
Epoch 39/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5384 - accuracy: 0.7381 - val_loss: 0.5547 - val_accuracy: 0.7307
Epoch 40/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5387 - accuracy: 0.7380 - val_loss: 0.5529 - val_accuracy: 0.7301
Epoch 41/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5385 - accuracy: 0.7382 - val_loss: 0.5533 - val_accuracy: 0.7300
Epoch 42/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5382 - accuracy: 0.7381 - val_loss: 0.5588 - val_accuracy: 0.7316
Epoch 43/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5387 - accuracy: 0.7388 - val_loss: 0.5549 - val_accuracy: 0.7275
Epoch 44/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5379 - accuracy: 0.7376 - val_loss: 0.5536 - val_accuracy: 0.7286
Epoch 45/100
751/751 [==============================] - 5s 6ms/step - loss: 0.5375 - accuracy: 0.7382 - val_loss: 0.5563 - val_accuracy: 0.7297
Epoch 46/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5378 - accuracy: 0.7376 - val_loss: 0.5562 - val_accuracy: 0.7299
Epoch 47/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5374 - accuracy: 0.7385 - val_loss: 0.5567 - val_accuracy: 0.7311
Epoch 48/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5371 - accuracy: 0.7378 - val_loss: 0.5551 - val_accuracy: 0.7306
Epoch 49/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5374 - accuracy: 0.7381 - val_loss: 0.5537 - val_accuracy: 0.7311
Epoch 50/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5371 - accuracy: 0.7385 - val_loss: 0.5539 - val_accuracy: 0.7323
Epoch 51/100
751/751 [==============================] - 5s 6ms/step - loss: 0.5371 - accuracy: 0.7383 - val_loss: 0.5545 - val_accuracy: 0.7312
Epoch 52/100
751/751 [==============================] - 5s 6ms/step - loss: 0.5370 - accuracy: 0.7392 - val_loss: 0.5536 - val_accuracy: 0.7310
Epoch 53/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5367 - accuracy: 0.7388 - val_loss: 0.5538 - val_accuracy: 0.7320
Epoch 54/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5363 - accuracy: 0.7394 - val_loss: 0.5551 - val_accuracy: 0.7329
Epoch 55/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5367 - accuracy: 0.7398 - val_loss: 0.5545 - val_accuracy: 0.7316
Epoch 56/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5365 - accuracy: 0.7390 - val_loss: 0.5563 - val_accuracy: 0.7307
Epoch 57/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5367 - accuracy: 0.7392 - val_loss: 0.5545 - val_accuracy: 0.7307

Epoch 58/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5361 - accuracy: 0.7393 - val_loss: 0.5553 - val_accuracy: 0.7308
Epoch 59/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5360 - accuracy: 0.7389 - val_loss: 0.5553 - val_accuracy: 0.7311
Epoch 60/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5362 - accuracy: 0.7381 - val_loss: 0.5533 - val_accuracy: 0.7302
Epoch 61/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5363 - accuracy: 0.7384 - val_loss: 0.5548 - val_accuracy: 0.7320
Epoch 62/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5362 - accuracy: 0.7394 - val_loss: 0.5576 - val_accuracy: 0.7301
Epoch 63/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5362 - accuracy: 0.7389 - val_loss: 0.5535 - val_accuracy: 0.7312
Epoch 64/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5356 - accuracy: 0.7395 - val_loss: 0.5543 - val_accuracy: 0.7316
Epoch 65/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5360 - accuracy: 0.7393 - val_loss: 0.5574 - val_accuracy: 0.7310
Epoch 66/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5358 - accuracy: 0.7394 - val_loss: 0.5564 - val_accuracy: 0.7317
Epoch 67/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5357 - accuracy: 0.7387 - val_loss: 0.5552 - val_accuracy: 0.7312
Epoch 68/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5356 - accuracy: 0.7385 - val_loss: 0.5562 - val_accuracy: 0.7315
Epoch 69/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5353 - accuracy: 0.7379 - val_loss: 0.5569 - val_accuracy: 0.7314
Epoch 70/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5352 - accuracy: 0.7396 - val_loss: 0.5564 - val_accuracy: 0.7309
Epoch 71/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5353 - accuracy: 0.7402 - val_loss: 0.5546 - val_accuracy: 0.7300
Epoch 72/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5352 - accuracy: 0.7390 - val_loss: 0.5563 - val_accuracy: 0.7296
Epoch 73/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5356 - accuracy: 0.7398 - val_loss: 0.5561 - val_accuracy: 0.7314
Epoch 74/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5353 - accuracy: 0.7393 - val_loss: 0.5577 - val_accuracy: 0.7312
Epoch 75/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5354 - accuracy: 0.7383 - val_loss: 0.5560 - val_accuracy: 0.7299
Epoch 76/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5354 - accuracy: 0.7392 - val_loss: 0.5573 - val_accuracy: 0.7313
Epoch 77/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5354 - accuracy: 0.7382 - val_loss: 0.5571 - val_accuracy: 0.7308
Epoch 78/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5351 - accuracy: 0.7388 - val_loss: 0.5569 - val_accuracy: 0.7305
Epoch 79/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5347 - accuracy: 0.7390 - val_loss: 0.5542 - val_accuracy: 0.7317
Epoch 80/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5348 - accuracy: 0.7400 - val_loss: 0.5583 - val_accuracy: 0.7279
Epoch 81/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5346 - accuracy: 0.7385 - val_loss: 0.5575 - val_accuracy: 0.7315
Epoch 82/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5347 - accuracy: 0.7400 - val_loss: 0.5562 - val_accuracy: 0.7310
Epoch 83/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5345 - accuracy: 0.7397 - val_loss: 0.5561 - val_accuracy: 0.7308
Epoch 84/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5344 - accuracy: 0.7402 - val_loss: 0.5573 - val_accuracy: 0.7310
Epoch 85/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5345 - accuracy: 0.7396 - val_loss: 0.5581 - val_accuracy: 0.7316
Epoch 86/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5351 - accuracy: 0.7400 - val_loss: 0.5586 - val_accuracy: 0.7311
Epoch 87/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5344 - accuracy: 0.7404 - val_loss: 0.5564 - val_accuracy: 0.7328
Epoch 88/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5349 - accuracy: 0.7408 - val_loss: 0.5578 - val_accuracy: 0.7312
Epoch 89/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5345 - accuracy: 0.7394 - val_loss: 0.5588 - val_accuracy: 0.7305
Epoch 90/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5345 - accuracy: 0.7395 - val_loss: 0.5572 - val_accuracy: 0.7311
Epoch 91/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5344 - accuracy: 0.7403 - val_loss: 0.5570 - val_accuracy: 0.7309
Epoch 92/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5345 - accuracy: 0.7401 - val_loss: 0.5568 - val_accuracy: 0.7319
Epoch 93/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5341 - accuracy: 0.7402 - val_loss: 0.5595 - val_accuracy: 0.7298
Epoch 94/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5343 - accuracy: 0.7400 - val_loss: 0.5573 - val_accuracy: 0.7326
Epoch 95/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5342 - accuracy: 0.7405 - val_loss: 0.5590 - val_accuracy: 0.7317
Epoch 96/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5342 - accuracy: 0.7394 - val_loss: 0.5571 - val_accuracy: 0.7304
Epoch 97/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5341 - accuracy: 0.7401 - val_loss: 0.5582 - val_accuracy: 0.7311
Epoch 98/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5341 - accuracy: 0.7403 - val_loss: 0.5590 - val_accuracy: 0.7293
Epoch 99/100
751/751 [==============================] - 4s 6ms/step - loss: 0.5342 - accuracy: 0.7400 - val_loss: 0.5572 - val_accuracy: 0.7315
Epoch 100/100
751/751 [==============================] - 4s 5ms/step - loss: 0.5343 - accuracy: 0.7406 - val_loss: 0.5574 - val_accuracy: 0.7316

In [37]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

8575/8575 - 0s - loss: 0.5578 - acc: 0.7263
Loss: 0.557812534073699, Accuracy: 0.7262973785400391

In [57]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save("AlphabetSoupCharity.h5")